import { WordMeaningData } from "./word-meaning.model";

export const sampleWordMeanings: WordMeaningData[] = [
  { word: "abate", meaning: "to reduce in amount, degree, or severity", difficulty: 2 },
  { word: "benevolent", meaning: "well meaning and kindly", difficulty: 3 },
  { word: "candid", meaning: "truthful and straightforward", difficulty: 1 },
  { word: "dauntless", meaning: "showing fearlessness and determination", difficulty: 4 },
  { word: "elucidate", meaning: "to make something clear; explain", difficulty: 3 },
  { word: "fervent", meaning: "having or displaying a passionate intensity", difficulty: 2 },
  { word: "gregarious", meaning: "fond of company; sociable", difficulty: 3 },
  { word: "haughty", meaning: "arrogantly superior and disdainful", difficulty: 4 },
  { word: "impeccable", meaning: "in accordance with the highest standards; faultless", difficulty: 5 },
  { word: "jubilant", meaning: "feeling or expressing great happiness and triumph", difficulty: 2 },
  { word: "keen", meaning: "having or showing eagerness or enthusiasm", difficulty: 1 },
  { word: "lucid", meaning: "expressed clearly; easy to understand", difficulty: 1 },
  { word: "meticulous", meaning: "showing great attention to detail; very careful and precise", difficulty: 4 },
  { word: "nonchalant", meaning: "feeling or appearing casually calm and relaxed", difficulty: 3 },
  { word: "obstinate", meaning: "stubbornly refusing to change one's opinion or chosen course of action", difficulty: 4 },
  { word: "pragmatic", meaning: "dealing with things sensibly and realistically", difficulty: 2 },
  { word: "quintessential", meaning: "representing the most perfect or typical example of a quality or class", difficulty: 5 },
  { word: "resilient", meaning: "able to withstand or recover quickly from difficult conditions", difficulty: 3 },
  { word: "serendipity", meaning: "the occurrence of events by chance in a happy or beneficial way", difficulty: 4 },
  { word: "tenacious", meaning: "tending to keep a firm hold of something; clinging or adhering closely", difficulty: 3 },
  { word: "ubiquitous", meaning: "present, appearing, or found everywhere", difficulty: 5 },
  { word: "venerable", meaning: "accorded a great deal of respect, especially because of age, wisdom, or character", difficulty: 4 },
  { word: "wistful", meaning: "having or showing a feeling of vague or regretful longing", difficulty: 3 },
  { word: "xenophile", meaning: "an individual who is attracted to foreign peoples, cultures, or customs", difficulty: 5 },
  { word: "yearn", meaning: "to have an intense feeling of longing for something", difficulty: 2 },
  { word: "zealous", meaning: "having or showing zeal", difficulty: 3 },
];
